force-app/main/default/objects/Bus__c/Bus__c.object-meta.xml
<CustomObject>
    <label>Bus</label>
    <nameField>
        <label>Bus Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bus__c/fields/Miles_Since_Last_Maintenance__c.field-meta.xml
<CustomField>
    <fullName>Miles_Since_Last_Maintenance__c</fullName>
    <formula>Odometer_Reading__c -  Last_Maintenance_Odometer_Reading__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Miles Since Last maintenance visit</inlineHelpText>
    <label>Miles Since Last Maintenance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bus_Maintenance__c/Bus_Maintenance__c.object-meta.xml
<CustomObject>
    <label>Bus Maintenance</label>
    <nameField>
        <label>Bus  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bus Maintenances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bus_Maintenance__c/fields/Bus__c.field-meta.xml
<CustomField>
    <fullName>Bus__c</fullName>
    <label>Bus</label>
    <referenceTo>Bus__c</referenceTo>
    <relationshipLabel>Bus Maintenances</relationshipLabel>
    <relationshipName>Bus_Maintenances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bus_Maintenance__c/fields/Garage__c.field-meta.xml
<CustomField>
    <fullName>Garage__c</fullName>
    <label>Garage</label>
    <referenceTo>Garage__c</referenceTo>
    <relationshipLabel>Bus Maintenances</relationshipLabel>
    <relationshipName>Bus_Maintenances</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Garage__c/Garage__c.object-meta.xml
<CustomObject>
    <label>Garage</label>
    <nameField>
        <label>Garage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Garages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BusMaintenanceJob.cls
global with sharing class BusMaintenanceJob implements Database.Batchable<sobject> {
    global Database.QueryLocator start(Database.BatchableContext BC){
        List<Garage__c> garages = [select id from Garage__c];
        return Database.getQueryLocator([select id from Bus__c where Miles_Since_Last_Maintenance__c > 5000 and Maximum_Capacity__c = '60' WITH SECURITY_ENFORCED]);
    }

    global void execute(Database.BatchableContext BC, List<Bus__c> scope){
       List<Bus_Maintenance__c> maintenanceList = new List<Bus_Maintenance__c>();
       for(Bus__c bus: scope){

       }
    } 

    global void finish(Database.BatchableContext BC){
    }
}